# Generated by Django 5.2.1 on 2025-05-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_ticket_check_in_time_ticket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
