# Generated by Django 5.0.2 on 2025-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_ticket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
