# Generated by Django 5.0.2 on 2025-05-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_tickettier_sold_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('KHALTI', 'Khalti'), ('CASH', 'Cash')], default='KHALTI', max_length=10),
        ),
    ]
