# Generated by Django 5.0.2 on 2025-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_ticket_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SOLD', 'Sold'), ('RESERVED', 'Reserved'), ('CANCELLED', 'Cancelled'), ('USED', 'Used')], default='PENDING', max_length=20),
        ),
    ]
