# Generated by Django 5.0.2 on 2025-05-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_ticket_cash_payment_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cash_verification_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
